networks:
  dungeon-service:
services:
  db:
    image: postgres:16.2-alpine
    restart: always
    container_name: local_dungeon_pg_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dungeon_pg_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d dungeon_pg_db -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 5
    profiles: ["all", "noapp"]
    networks:
        - dungeon-service
  app:
    image: dungeoncrawler:latest
    restart: always
    container_name: local_dungeoncrawler
    ports:
      - "8000:8000"
    command: ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    profiles: ["all"]
    networks:
        - dungeon-service

volumes:
  pgdata:
