from typing import Optional

from sqlmodel import Field, Relationship, SQLModel


class CharacterBase(SQLModel):
    name: str
    hero_class: str
    biography: str
    description: str
    age: int


class CharacterCreate(CharacterBase):
    pass


class CharacterDescriptionCreate(SQLModel):
    description: str


# TODO: add inventory, status
class Character(CharacterBase, table=True):
    id: int | None = Field(default=None, primary_key=True)
    campaign_id: int | None = Field(default=None, foreign_key="campaign.id")
    campaign: Optional["Campaign"] = Relationship(back_populates="characters")  # type: ignore[name-defined]
    # name: str
    # hero_class: str
    # level: int | None = 1
    # biography: str  # generated by ai?
    # description: str  # created via a back and forth with the ai
    strength: int | None
    perception: int | None
    endurance: int | None
    charisma: int | None
    intelligence: int | None
    agility: int | None
    luck: int | None
