from sqlmodel import Field, SQLModel


class Character(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    name: str
    hero_class: str
    level: int | None
    biography: str  # generated by ai?
    description: str  # created via a back and forth with the ai
    story_so_far: (
        str | None
    )  # ? not sure yet, maybe storing per character context snippets
    age: int | None
    stength: int | None
    perception: int | None
    endurance: int | None
    charisma: int | None
    intelligence: int | None
    agility: int | None
    luck: int | None
