from sqlmodel import Field, SQLModel


class CharacterBase(SQLModel):
    name: str
    hero_class: str
    biography: str
    description: str
    age: int


class CharacterCreate(CharacterBase):
    pass


class CharacterDescriptionCreate(SQLModel):
    description: str


class Character(CharacterBase, table=True):
    id: int | None = Field(default=None, primary_key=True)
    # name: str
    # hero_class: str
    # level: int | None = 1
    # biography: str  # generated by ai?
    # description: str  # created via a back and forth with the ai
    story_so_far: str | None
    strength: int | None
    perception: int | None
    endurance: int | None
    charisma: int | None
    intelligence: int | None
    agility: int | None
    luck: int | None
